<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no; address=no; email=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>微信商城</title>
    <link rel="stylesheet" href="<?php echo $this->getResourceUrl()?>css/main.css?<?php echo time();?>">
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/libs/jquery-2.0.3.min.js"></script>
    <script type="text/javascript">
		var web_path = "<?php echo $this->config['global']['path']?>";
		var source = 2;//weixin
	</script>
</head>
<body id="help">
	<header class="header">
		<h1>帮助中心<a href="<?php echo $this->config['global']['path']?>mobile/goods/index"><img src="<?php echo $this->getResourceUrl()?>img/arrow-left.png" alt=""></a></h1>
	</header>
	<div class="wrapper">
		<div class="cont">
			<ul class="tab3_title">
				<li class="cur"><a href="javascript:;">常见问题</a></li>
				<li><a href="javascript:;">微商城下单教程</a></li>
				<li><a href="javascript:;">微信绑定支付流程</a></li>
			</ul>
			<div class="tab3_con">
				<div>
					<h3>微商城常见问题</h3>
					<dl>
						<dt>【购买须知】</dt>
						<dd>1.关注微信服务号，点击下方菜单<span class="cl_org">[伊仔的店]</span>中的<span class="cl_org">[微信专享价]</span>，即刻参与：<span class="cl_org b">全场19.9元包邮，天天美味GO！</span></dd>
						<dd>2.<span class="cl_org">每天7：30</span>美味贴心组合装<span class="cl_org">3款</span>上新，邀伊粉们专享的微信特惠价：<span class="cl_org">全场19.9元包邮！</span></dd>
						<dt>【发货须知】</dt>
						<dd>1.<span class="b">发货时间</span>：本单成功付款后2个工作日内发货，购买2款组合装及以上，需分开购买支付，同一收货地址、收货人的48小时内订单，将合并发货。</dd>
						<dd>2.<span class="b">包邮告知</span>：微信专享每单承诺包邮，默认使用海航天天、韵达快递或申通快递（按地区权宜发送，不可指定）。</dd>
						<dd>3.<span class="b">派送范围</span>：国内（除特别偏远，上述快递无法送达的区域外）均可派送。</dd>
						<dd>4.请务必填写准确的快递信息，如因提供的信息错误造成不必要的损失，此损失全部由消费者自行承担。</dd>
						<dt>【售后服务】</dt>
						<dd>1.如有任何问题请拨打客服专线处理。<br/><span class="cl_org">客服专线：400-8819-777<br/>（客服时间：9:00-21:00）</span></dd>
						<dd>2.<span class="b">售后订单处理：</span> </dd>
						<dd>A.<span class="b">查看发货详情：<br/></span>请拨打客服专线：400-8819-777。</dd>
						<dd>B.<span class="b">退款：</span>请拨打客服专线：400-8819-777，审核通过后，将在10个工作日内，全额退还到您的支付账户中。</dd>
					</dl>
				</div>
				<div class="none">
					<h3>微商城下单教程</h3>
					<img src="<?php echo $this->getResourceUrl()?>img/help_jc.jpg">
				</div>
				<div class="none">
					<h3>微信绑定支付流程</h3>
					<img src="<?php echo $this->getResourceUrl()?>img/help_zf1.jpg" class="fl">
					<img src="<?php echo $this->getResourceUrl()?>img/help_zf2.jpg" class="fl">
					<img src="<?php echo $this->getResourceUrl()?>img/help_zf3.jpg" class="fl">
				</div>
			</div>
		</div>
	</div>
	 <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/lyfen.js?<?php echo time();?>"></script>
	 <script type="text/javascript">

        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
             WeixinJSBridge.call('hideToolbar');
        });
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            // 发送给好友
            WeixinJSBridge.on('menu:share:appmessage', function(argv){
                shareFriendOrTimeline("sendAppMessage","send_msg");
            });
            // 分享到朋友圈
            WeixinJSBridge.on('menu:share:timeline', function(argv){
                shareFriendOrTimeline("shareTimeline","timeline");
            });
         }, false);

        var shareFriendOrTimeline = function(invokeType,reportType) {
            WeixinJSBridge.invoke(invokeType,{
                //"appid":window.shareData.appid,
                "img_url":'http://wx.laiyifen.com/html/m/img/share.jpg',
                "img_width":"100",
                "img_height":"100",
                "link":"http://wx.laiyifen.com/mobile/goods/index",
                "desc":"",
                "title":"微商城19.9元限时包邮"
                }, function(res) {
                     _report(reportType, res.err_msg);
            });
        };
    </script>
	
</body>
</html>