<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝</title>
    <meta name="keyword" content="快来参与吧 - 邀请闺蜜">
    <meta name="description" content="快来参与吧 - 邀请闺蜜">

    <!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css?v=<?php echo $this->version;?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=<?php echo $this->version;?>"/>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php echo $this->version;?>"></script>
</head>
<body>
<div class="page_box" id="invitationM_box">
    <div class="page_wrap">
        <div class="wrap_invitationM"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/invitation/invitation_m.jpg"></div>
    </div>
</div>

<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/module.share.js?v=0.3"></script>
<script type="text/javascript">
    var op = {
        isHideButton : false,
        shareTitle : "好东西就要分享给闺蜜！",
        shareDescription : "姐妹们，不可错过的经期小助手，快来关注吧！",
        //shareLink : 'http://mp.weixin.qq.com/s?__biz=MjM5MjUxMTQ3Mg==&amp;mid=200144027&amp;idx=1&amp;sn=ce02c97dbb6b905679c692a34da6ecc8#rd',
        shareLink : '<?php echo $this->inviteUrl;?>',
        shareImgUrl : 'http://kotexcrm.umaman.com/html/img/share_invitation.jpg'
    };
    WeixinShareSetting(op);
</script>
</body>
</html>