<!-- start order statistics -->
<div class="list-div">
<table cellspacing='1' cellpadding='3'>
<tr>
<th colspan="8" class="group-title">订单统计信息</th>
</tr>
<tr>
<td width="12.5%">未支付订单数(今日):</td>
<td width="12.5%"><strong><?php echo $this->order['daily_unpay'];?></strong></td>
<td width="12.5%">已支付,待发货订单数(今日):</td>
<td width="12.5%"><strong><?php echo $this->order['daily_paid_unship'];?></strong></td>
<td width="12.5%">已发货订单数(今日):</td>
<td width="12.5%"><strong><?php echo $this->order['daily_shipped'];?></strong></td>
<td width="12.5%">已取消订单数(今日):</td>
<td width="12.5%"><strong><?php echo $this->order['daily_cancel'];?></strong></td>
</tr>

<tr>
<td width="12.5%">未支付订单数(本周):</td>
<td width="12.5%"><strong><?php echo $this->order['weekly_unpay'];?></strong></td>
<td width="12.5%">已支付,待发货订单数(本周):</td>
<td width="12.5%"><strong><?php echo $this->order['weekly_paid_unship'];?></strong></td>
<td width="12.5%">已发货订单数(本周):</td>
<td width="12.5%"><strong><?php echo $this->order['weekly_shipped'];?></strong></td>
<td width="12.5%">已取消订单数(本周):</td>
<td width="12.5%"><strong><?php echo $this->order['weekly_cancel'];?></strong></td>
</tr>

<tr>
<td width="12.5%">未支付订单数(本月):</td>
<td width="12.5%"><strong><?php echo $this->order['monthly_unpay'];?></strong></td>
<td width="12.5%">已支付,待发货订单数(本月):</td>
<td width="12.5%"><strong><?php echo $this->order['monthly_paid_unship'];?></strong></td>
<td width="12.5%">已发货订单数(本月):</td>
<td width="12.5%"><strong><?php echo $this->order['monthly_shipped'];?></strong></td>
<td width="12.5%">已取消订单数(本月):</td>
<td width="12.5%"><strong><?php echo $this->order['monthly_cancel'];?></strong></td>
</tr>

</table>
</div>
<br />

<!-- end order statistics -->

<!-- start system information -->
<div class="list-div">
<table cellspacing='1' cellpadding='3'>
<tr>
<th colspan="4" class="group-title">系统信息</th>
</tr>
<tr>
<td width="20%">服务器操作系统:</td>
<td width="30%"><?php echo $this->sys_info['os'];?> (<?php echo $this->sys_info['ip'];?>)</td>
<td width="20%">Web 服务器:</td>
<td width="30%"><?php echo $this->sys_info['web_server'];?></td>
</tr>
<tr>
<td>PHP 版本:</td>
<td><?php echo $this->sys_info['php_ver'];?></td>
<td>MySQL 版本:</td>
<td><?php echo $this->sys_info['mysql_ver'];?></td>
</tr>
<tr>
<td>安全模式:</td>
<td><?php echo $this->sys_info['safe_mode'];?></td>
<td>安全模式GID:</td>
<td><?php echo $this->sys_info['safe_mode_gid'];?></td>
</tr>
<tr>
<td>Socket 支持:</td>
<td><?php echo $this->sys_info['socket'];?></td>
<td>时区设置:</td>
<td><?php echo $this->sys_info['timezone'];?></td>
</tr>
<tr>
<td>GD 版本:</td>
<td><?php echo $this->sys_info['gd'];?></td>
<td>Zlib 支持:</td>
<td><?php echo $this->sys_info['zlib'];?></td>
</tr>
<tr>
<td>编码:</td>
<td>UTF-8</td>
<td></td>
<td></td>
</tr>
</table>
</div>