<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>微信商城</title>
    <meta name="description" content="">
    <!--移动平台-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no, address=no, email=no">
    <meta http-equiv="cleartype" content="on">


    <!--For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94-->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="">


    <link rel="stylesheet" type="text/css" href="<?php echo $this->getResourceUrl()?>css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getResourceUrl()?>css/style.css"/>
    <style>body{ overflow-x: hidden;}</style>
    <script type="text/javascript">
		var web_path = "<?php echo $this->config['global']['path']?>";
		var html_web_path = "<?php echo $this->getResourceUrl()?>";
	</script>
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/seajs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/seajs/seajsConfig.js"></script>
</head>
<body>
    <div id="loading"></div>

    <div class="wrapper" id="productDetail">
       <header id="header">
            <ul>
                <li><a class="pCenter" href="<?php echo $this->config['global']['path']?>weixinshop/shoppingcart2/index">购物车</a></li>
                <li><a class="shapping-cat" href="<?php echo $this->config['global']['path']?>weixinshop/order/list">个人中心</a></li>
           </ul>
           <a href="javascript:window.history.go(-1);" class="btn-back"></a>
        </header> 
       <div class="banner">
            <ul class="swipe-wrap">
                <?php for ($i = 2; $i < 11; $i++) {?>
                <?php if(!empty($this->goods['gpic'.$i])){?>
                <li><img class="img100" src="<?php echo $this->goods['gpic'.$i]?>"></li>  
                <?php }?>
                <?php }?>
            </ul>
            <ul class="dot clearfix" >
                <?php $picNum = 0;?>
                <?php for ($i = 2; $i < 11; $i++) {?>
                <?php if(!empty($this->goods['gpic'.$i])){?>
                <?php $picNum ++;?>
                <li <?php if($picNum == 1){?>class="on"<?php }?>><?php echo $picNum?></li>
                <?php }?>
                <?php }?>
            </ul>
        </div>
        
        <div class="bar-top-bottom">
            <h2><?php echo $this->goods['name']?></h2>
            <p>售价：<strong>￥<?php echo showMoney($this->goods['prize']/100)?></strong></p>
        </div>
        
        <div class="bar-top-bottom">
           
        </div>
        
        
        <ul class="detail-tab">
            <li class="on">产品详情</li>
            <li>产品参数</li>
        </ul>
        <ul class="detail-tab-cont">
        <!-- 
            <li class="on"><img src="<?php echo $this->goods['gdetail_pic1']?>" alt=""></li>
             -->
            <li class="on"><?php echo $this->goods['desc']?></li>
            <li><img src="<?php echo $this->goods['gparams_pic1']?>" alt=""></li>
        </ul>
        
        <div class="fixed-bottom">
            <?php if(!empty($this->goods['stock_num']) && $this->goods['stock_num']>0 ){?>
            <a href="javascript:;" class="btn-buy" gid="<?php echo $this->goods['gid']?>">立即购买</a>
            <a href="javascript:;" class="btn-put" gid="<?php echo $this->goods['gid']?>">放入购物车</a>
            <?php }else{?>
            <a href="javascript:;" class="btn-disabled">暂时缺货</a>                  
            <?php }?>
        </div>
    </div>
    
    <div class="pop" id="pop-confirm">
    	<p>该商品已加入购物车</p>
        <div><a class="popUpBtn" data-rule="close" href="javascript:;">继续购物</a>&nbsp;&nbsp;<a class="popUpBtn" href="<?php echo $this->config['global']['path']?>weixinshop/shoppingcart2/index">立即结算</a></div>
    </div>
	
    <script type="text/javascript">
        window.onload = function() {
            document.getElementById("loading").style.display = "none";
       }
        seajs.use("app/views-productDetail");
    </script>
</body>
</html>
