<!doctype html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no; address=no; email=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="<?php echo $this->getResourceUrl()?>css/main.css">
</head>
<body id="list">
	<header class="header">
		<h1>订单列表<a href="<?php echo $this->config['global']['path']?>mobile/goods/index"><img src="<?php echo $this->getResourceUrl()?>img/arrow-left.png" alt=""></a></h1>
	</header>
	<div class="wrapper">
		<div class="cont">
			<?php if(!empty($this->orderList['datas'])){?>
				<?php foreach ($this->orderList['datas'] as $order) {?>
				<h3 class="row">
					<p>订单号:<span><?php echo $order['out_trade_no']?></span></p>
					<i class="payed">已支付</i>
				</h3>
				<div class="pro">
					<div class="pic">
						<img src="<?php echo $order['goodsInfo']['gpic1']?>" alt="">
					</div>
					<div class="det">
						<h4>【<span><?php echo $order['goodsInfo']['gname']?></span>】</h4>
						<p class="pri">总额：<span>￥<?php echo showMoney($order['total_fee']/100)?></span></p>
						<p class="time">时间：<?php echo date("Y-m-d",strtotime($order['time_end']))?></p>
						<a href="<?php echo $this->config['global']['path']?>mobile/order/detail?out_trade_no=<?php echo $order['out_trade_no']?>" class="btn btn-detail">
							<img src="<?php echo $this->getResourceUrl()?>img/btn-detail.png" alt="">
						</a>
					</div>
				</div>
				<?php } ?>
			<?php }else { ?>
				<!-- 没有订单 -->
				<div class="no-order">
					<div class="success">
						<img src="<?php echo $this->getResourceUrl()?>img/order-no.jpg" alt="">
					</div>
				</div>
				<a href="<?php echo $this->config['global']['path']?>mobile/goods/index" class="btn btn-ljqg">
					<img src="<?php echo $this->getResourceUrl()?>img/btn-ljqg.png" alt="">
				</a>

			<?php } ?>
		</div>
	</div>
	 <script type="text/javascript">

        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
             WeixinJSBridge.call('hideToolbar');
        });
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            // 发送给好友
            WeixinJSBridge.on('menu:share:appmessage', function(argv){
                shareFriendOrTimeline("sendAppMessage","send_msg");
            });
            // 分享到朋友圈
            WeixinJSBridge.on('menu:share:timeline', function(argv){
                shareFriendOrTimeline("shareTimeline","timeline");
            });
         }, false);

        var shareFriendOrTimeline = function(invokeType,reportType) {
            WeixinJSBridge.invoke(invokeType,{
                //"appid":window.shareData.appid,
                "img_url":'http://wx.laiyifen.com/html/m/img/share.jpg',
                "img_width":"100",
                "img_height":"100",
                "link":"http://wx.laiyifen.com/mobile/goods/index",
                "desc":"",
                "title":"来伊份微商城19.9元限时包邮"
                }, function(res) {
                     _report(reportType, res.err_msg);
            });
        };
    </script>
</body>
</html>