<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>微信商城</title>
    <meta name="description" content="">
    <!-- 移动平台-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no, address=no, email=no">
    <meta http-equiv="cleartype" content="on">


    <!--For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94-->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="">


    <link rel="stylesheet" type="text/css" href="<?php echo $this->getResourceUrl()?>css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getResourceUrl()?>css/style.css"/>
    <script type="text/javascript">
		var web_path = "<?php echo $this->config['global']['path']?>";
		var html_web_path = "<?php echo $this->getResourceUrl()?>";
	</script>
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/seajs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/seajs/seajsConfig.js"></script>
</head>
<body>
    <div class="wrapper" id="orderlist">
       <header id="header">
           <a href="javascript:window.history.go(-1);" class="btn-back"></a>
           <span class="headerTitle">订单列表</span>
       </header>
       <div class="container">
         <div class="list">
         <?php echo $this->partial('order/partials/order_list.phtml',$this); ?>
         </div>
         <?php if($this->is_more){?>
         <a href="javascript:;" class="btn-loadmore">点击加载剩余订单</a>
         <?php }else{?>
         <a href="javascript:;" class="btn-loadmore disabled">没有更多订单了</a>
         <?php }?>
       </div>
    </div>
    
<script type="text/javascript">
  seajs.use("app/viewItem", function(view) {
     view.orderList();
  });
</script>
</body>
</html>