<form action='/question/index/answer' method='post'>
<?php 
foreach ($this->question['question'] as $key => $val)
{
	echo $key.'、';
	echo $val['question']."<br>";
	if($val['type'] == 1)
	{
		foreach ($val['options'] as $k => $v)
		{
			echo '<input type="radio" name="answer['.$key.']" value="'.$v['key'].'" />'.$v['option'].'<br>';
		}
	}
	else if($val['type'] == 2)
	{
	    foreach ($val['options'] as $k => $v)
	    {
	    	echo '<input type="checkbox" name="answer['.$key.'][]" value="'.$v['key'].'" />'.$v['option'].'<br>';
	    }
	}
	else 
	{
		echo '<input type="text" name="answer['.$key.']" />'.'<br>';
	}
}
?>
<input type='hidden' name='code' value='<?php echo $this->naire;?>'>
<input type='hidden' name='user_id' value='<?php echo $this->user;?>'>
<input type='hidden' name='randId' value='<?php echo $this->question['randId'];?>'>
<input type='submit' value='submit'>
</form>