 <head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> </head>
<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <?php 
    if($this->p == 1)
    {
    ?>
	    <form method='post' action='/index/image'  enctype="multipart/form-data">
	    <input type='file' name = 'file1'><br>
	    <input type='file' name = 'file2'><br>
	    <input type='submit' name='b' value='对比' />
    </form>
    <?php 
    }
    else
    {
    ?>
    <table>
    <tr align='center'><td width='250px'><img width='250px' src='<?php echo $this->img1;?>' /></td><td width='250px'><img width='250px' src='<?php echo $this->img2;?>' /></td></tr>
    <tr><td colspan='2'>对比结果：<?php echo $this->xs?'相似':'不相似';?></td></tr>
    <tr><td colspan='2'><a href='/index/image'>重新比较</a></td></tr>
    </table>
    <?php 
    }
    ?>
</div>