<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝</title>
    <meta name="keyword" content="我的信息">
    <meta name="description" content="我的信息">

    <!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=1.7"/>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php $this->version;?>"></script>
    <script>var datas = '<?php echo $this->datas;?>';</script>
    <script type="text/javascript">
        var _hmt = _hmt || [];
    </script>
    </head>
<body>
<div class="loading_box" id="loading_box"><img src="<?php echo $this->rootPath;?>html/img/loading.gif"></div>
<div class="page_box" id="calendar_box">
    <div class="page_bg"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/calendar/calendar_bg.jpg"></div>
    <div class="page_wrap">
        <div class="wrap_user">
            <div class="calendar_pannel">
                <img class="pannel_icon left_pannel_icon" src="<?php echo $this->rootPath;?>html/img/calendar/calendar_iconTip.png">
                <img class="pannel_icon right_pannel_icon" src="<?php echo $this->rootPath;?>html/img/calendar/calendar_iconTip.png">
                <a onclick="_hmt.push(['_trackEvent', '蜜历', '点击次数']);" class="date_show" href="<?php echo $this->rootPath;?>campaign/calendar/photo?FromUserName=<?php echo $this->openid;?>"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/calendar/calendar_dateShow.png"></a>
                <div class="calendar_wrap">
                    <div class="calendar_content">
                        <img class="calendar_bottomRight" src="<?php echo $this->rootPath;?>html/img/calendar/calendar_bottomRightBg.png">
                        <div class="pannel_top">
                            <img class="calendar_title" src="<?php echo $this->rootPath;?>html/img/calendar/calendar_title.png">
                            <div class="days_show">
                                <i class="prev_btn"><img src="<?php echo $this->rootPath;?>html/img/calendar/calendar_prevMonth.png"></i>
                                <p class="days_box"><span class="year">2014</span>年<span class="month">3</span>月</p>
                                <i class="next_btn"><img src="<?php echo $this->rootPath;?>html/img/calendar/calendar_nextMonth.png"></i>
                            </div>
                        </div>
                        <div class="calendar_body">
                            <div class="calender_weeks">
                                <ul>
                                    <li><span>日</span></li>
                                    <li><span>一</span></li>
                                    <li><span>二</span></li>
                                    <li><span>三</span></li>
                                    <li><span>四</span></li>
                                    <li><span>五</span></li>
                                    <li><span>六</span></li>
                                </ul>
                            </div>
                            <div class="calenter_days">
                                <ul>
                                    <!-- JS自动生成的数据 Begin -->
                                    <!--<li class="prev_month" year="2013" month="2" day="23"><span>23</span></li>-->
                                    <!--<li class="prev_month" year="2013" month="2" day="24"><span>24</span></li>-->
                                    <!--<li class="prev_month" year="2013" month="2" day="25"><span>25</span></li>-->
                                    <!--<li class="prev_month" year="2013" month="2" day="26"><span>26</span></li>-->
                                    <!--<li class="prev_month"><span>27</span></li>-->
                                    <!--<li class="prev_month"><span>28</span></li>-->
                                    <!--<li class="now_month daysicon_yjq"><span>1</span></li>-->
                                    <!--<li class="now_month daysicon_yjq"><span>2</span></li>-->
                                    <!--<li class="now_month daysicon_yjq"><span>3</span></li>-->
                                    <!--<li class="now_month daysicon_yjq"><span>4</span></li>-->
                                    <!--<li class="now_month daysicon_yjq"><span>5</span></li>-->
                                    <!--<li class="now_month daysicon_yjq"><span>6</span></li>-->
                                    <!--<li class="now_month daysicon_yyq"><span>7</span></li>-->
                                    <!--<li class="now_month daysicon_yyq daysicon_pnr"><i></i><span>8</span></li>-->
                                    <!--<li class="now_month daysicon_yyq"><span>9</span></li>-->
                                    <!--<li class="now_month daysicon_ycyjq"><span>10</span></li>-->
                                    <!--<li class="now_month daysicon_ycyjq"><span>11</span></li>-->
                                    <!--<li class="now_month daysicon_ycyjq"><span>12</span></li>-->
                                    <!--<li class="now_month daysicon_ycyjq"><span>13</span></li>-->
                                    <!--<li class="now_month"><span>14</span></li>-->
                                    <!--<li class="now_month"><span>15</span></li>-->
                                    <!--<li class="now_month"><span>16</span></li>-->
                                    <!--<li class="now_month"><span>17</span></li>-->
                                    <!--<li class="now_month"><span>18</span></li>-->
                                    <!--<li class="now_month"><span>19</span></li>-->
                                    <!--<li class="now_month"><span>20</span></li>-->
                                    <!--<li class="now_month"><span>21</span></li>-->
                                    <!--<li class="now_month"><span>22</span></li>-->
                                    <!--<li class="now_month"><span>23</span></li>-->
                                    <!--<li class="now_month"><span>24</span></li>-->
                                    <!--<li class="now_month"><span>25</span></li>-->
                                    <!--<li class="now_month"><span>26</span></li>-->
                                    <!--<li class="now_month"><span>27</span></li>-->
                                    <!--<li class="now_month"><span>28</span></li>-->
                                    <!--<li class="now_month"><span>29</span></li>-->
                                    <!--<li class="now_month"><span>30</span></li>-->
                                    <!--<li class="now_month"><span>31</span></li>-->
                                    <!--<li class="next_month"><span>1</span></li>-->
                                    <!--<li class="next_month"><span>2</span></li>-->
                                    <!--<li class="next_month"><span>3</span></li>-->
                                    <!--<li class="next_month"><span>4</span></li>-->
                                    <!--<li class="next_month"><span>5</span></li>-->
                                    <!-- JS自动生成的数据 End -->
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="calendar_legend"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/calendar/calendar_dateTip.png"></div>
            </div>
            <div class="control_pannel">
                <ul>
                    <li>
                        <span class="fl fsBiger">月经开始时间</span>
                        <p class="setting_option start_setting fr">
                            <img class="option_off" src="<?php echo $this->rootPath;?>html/img/calendar/option_unchoose.png">
                            <img class="option_on" src="<?php echo $this->rootPath;?>html/img/calendar/option_choose.png">
                        </p>
                    </li>
                    <li>
                        <span class="fl fsBiger">月经结束时间</span>
                        <p class="setting_option end_setting fr">
                            <img class="option_off" src="<?php echo $this->rootPath;?>html/img/calendar/option_unchoose.png">
                            <img class="option_on" src="<?php echo $this->rootPath;?>html/img/calendar/option_choose.png">
                        </p>
                    </li>
                </ul>
            </div>
<!--             <div class="control_pannel">
                <img class="start_text fl" src="<?php echo $this->rootPath;?>html/img/calendar/text_start.png" alt="月经开始时间">
                <p class="setting_option start_setting fl">
                    <img class="option_img option_off" src="<?php echo $this->rootPath;?>html/img/calendar/option_off.png">
                    <img class="option_img option_on" src="<?php echo $this->rootPath;?>html/img/calendar/option_on.png">
                    <img class="option_btn" src="<?php echo $this->rootPath;?>html/img/calendar/option_btn.png">
                </p>
                <p class="setting_option end_setting fr">
                    <img class="option_img option_off" src="<?php echo $this->rootPath;?>html/img/calendar/option_off.png">
                    <img class="option_img option_on" src="<?php echo $this->rootPath;?>html/img/calendar/option_on.png">
                    <img class="option_btn" src="<?php echo $this->rootPath;?>html/img/calendar/option_btn.png">
                </p>
                <img class="end_text fr" src="<?php echo $this->rootPath;?>html/img/calendar/text_end.png" alt="月经结束时间">
            </div> -->
        </div>
    </div>
</div>
<script type="text/javascript">
    seajs.use(["jquery","views.calendar"],function($,calendarPage){
        $(function(){
            calendarPage.init();
        })
    })
</script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/module.share.js?v=0.3"></script>
<script type="text/javascript">
    var op = {
        isHideButton : false,
        shareTitle : "用微信记录经期，无忧生活我做主！",
        shareDescription : "无忧日历记录你的每日经期状态，有了ta，经期预测易如反掌啦！",
        shareLink : location.href,
        shareImgUrl :  "http://kotexcrm.umaman.com/html/img/share_calendar.jpg"
    };
    WeixinShareSetting(op);
</script>
</body>
</html>