<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝</title>
    <meta name="keyword" content="高洁丝 无忧日历">
    <meta name="description" content="高洁丝 无忧日历">

	<meta http-equiv="Expires" Content="0">
	<!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css?v=<?php echo $this->version;?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=<?php echo $this->version;?>"/>
 
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php echo $this->version;?>"></script>
</head>
<body>
<div class="page_box">
    <img src="<?php echo $this->rootPath;?>html/img/video/care.jpg" width="100%" alt="">
    <a href="http://mp.weixin.qq.com/s?__biz=MjM5MjUxMTQ3Mg==&mid=200144027&idx=1&sn=ce02c97dbb6b905679c692a34da6ecc8#rd"><img src="<?php echo $this->rootPath;?>html/img/video/btn_care.png" class="btn_care" alt="" width="62%"></a>
<!--     <div class="share_tan" style="display:none;">
        <img src="<?php echo $this->rootPath;?>html/img/video/img_share.jpg" class="img100" alt="">
        <img src="<?php echo $this->rootPath;?>html/img/video/btn.gif" class="btn_know" alt="">
    </div> -->
</div>
<!--  
<?php echo $this->openid;?><br />
<?php echo $this->invitedOpenid;?>
-->

<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/module.share.js?v=0.3"></script>
<script type="text/javascript">
    var op = {
        isHideButton : false,
        shareTitle : "经期管理好帮手！",
        shareDescription : "亲们，我有一个经期管理好帮手哦！你也来试试吧！",
        shareLink : location.href,
        shareImgUrl : "http://kotexcrm.umaman.com/html/img/video/care.jpg"
    };
    WeixinShareSetting(op);
</script>
</body>
</html>