<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝</title>
    <meta name="keyword" content="快来参与吧 - 无忧蜜历">
    <meta name="description" content="快来参与吧 - 无忧蜜历">

    <!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=<?php $this->version;?>"/>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php echo time();?>"></script>
</head>
<body>
<div class="page_box" id="user_lead_box">
    <div class="page_bg"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/userInfo/userInfo_bg.jpg"></div>
    <div class="page_wrap">
        <div class="wrap_lead">
            <div class="lead_img"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/userInfo/lead_page.jpg"></div>
            <a class="lead_btn" href="<?php echo $this->rootPath;?>campaign/calendar/user-info?FromUserName=<?php echo $this->openid;?>"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/userInfo/lead_btn.png"></a>
        </div>
    </div>
</div>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>

</body>
</html>