<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝</title>
    <meta name="keyword" content="今日蜜历，无忧蜜历">
    <meta name="description" content="今日蜜历，无忧蜜历">

    <!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=1.3"/>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php $this->version;?>"></script>
    <script type="text/javascript">
        var _hmt = _hmt || [];
    </script>
<body>
<div class="page_box" id="user_box">
    <div class="page_bg"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/user/userInfo_bg.jpg"></div>
    <div class="page_wrap">
        <div class="wrap_user">
            <div class="user_info">
                <a onclick="_hmt.push(['_trackEvent', '日历', '点击次数']);" class="user_calendar" href="<?php echo $this->rootPath;?>campaign/calendar/calendar?FromUserName=<?php echo $this->openid;?>"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/user/userInfo_icon_calendar.png"></a>
                <img class="user_icon_tip" src="<?php echo $this->rootPath;?>html/img/user/userInfo_icon_tip.png">
                <div class="user_info_show">
                    <div class="info_show">
                        <div class="info_show_text">
                            <div class="daysInfo_show">
                                <a class="prev_day" href="?date=<?php echo $this->preDay;?>&FromUserName=<?php echo $this->openid;?>"><img src="<?php echo $this->rootPath;?>html/img/user/userInfo_prevDay.png"></a>
                                <span><b class="year"><?php echo $this->year;?></b>年<b class="month"><?php echo $this->month;?></b>月<b class="day"><?php echo $this->day;?></b>日</span>
                                <a class="next_day" href="?date=<?php echo $this->postDay;?>&FromUserName=<?php echo $this->openid;?>"><img src="<?php echo $this->rootPath;?>html/img/user/userInfo_nextDay.png"></a>
                            </div>
                            <p class="fslarger"><span><?php echo $this->title;?></span></p>
                            <p class="fsBiger"><img class="icon_highHeart" src="<?php echo $this->rootPath;?>html/img/icon_highHeart.png"><span><?php echo $this->content;?></span></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="user_game">
                <div class="picture_box">
                    <img class="userInfo_photo_start" src="<?php echo $this->rootPath;?>html/img/user/userInfo_photo_start.png">
                    <div class="picture_img">
                        <!-- 如果用户未上传头像，显示默认头像 -->
                        <?php if($this->photo) { ?>
                        <img class="fullWidth" src="<?php echo $this->photo;?>/w/400">
                        <?php } else { ?>
                        <img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/user/userInfo_photo_default.jpg">
                        <?php }?>
                        <!-- 如果用户已上传头像，显示用户头像 -->
                    </div>
                    <img class="userInfo_photo_bg" src="<?php echo $this->rootPath;?>html/img/user/userInfo_photo_bg.png">
                </div>
                <div class="dayIcon_box">
                <?php if(!empty($this->picture)) {?><img class="fullWidth" src="<?php echo $this->picture;?>"><?php }else { ?><img class="fullWidth" src="<?php echo $this->rootPath;?>html/test/dayIcon_test.png"><?php }?></div>
            </div>
        </div>
    </div>
</div>

<div id="tool_box">
    <a href="javascript:;" class="wheel-button nw">
        <img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/user/tool_trigger.png">
    </a>
    <ul id="wheel3" class="wheel">
        <li class="item item_share"><a onclick="_hmt.push(['_trackEvent', '转发', '点击次数']);" href="<?php echo $this->rootPath;?>campaign/calendar/share?FromUserName=<?php echo $this->openid;?>&date=<?php echo date("Y-m-d");?>&tip_id=<?php echo $this->tip_id;?>"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/user/tool_btn_share.png"></a></li>
        <li class="item item_uploadPic"><a onclick="_hmt.push(['_trackEvent', '照片', '点击次数']);" href="<?php echo $this->rootPath;?>html/uploadtip.html?FromUserName=<?php echo $this->openid;?>"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/user/tool_btn_upload.png"></a></li>
        <li class="item item_shake"><a onclick="_hmt.push(['_trackEvent', '摇一摇', '点击次数']);" href="<?php echo $this->rootPath;?>html/yaoyiyao.html?FromUserName=<?php echo $this->openid;?>"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/user/tool_btn_shake.png"></a></li>
    </ul>
    <div class="wheel_bg"><div class="wheel_bg_circle"></div></div>
</div>

<script type="text/javascript">
    seajs.use(["jquery","views.user"],function($,userPage){
        $(function(){
            userPage.init();
        })
    })
</script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/module.share.js?v=0.3"></script>
<script type="text/javascript">
    var op = {
    	isHideButton : false,
    	shareTitle : "每日健康提醒小贴士~",
    	shareDescription : "每日健康小贴士，让你在特殊时期也能备受呵护哦！",
    	shareLink : location.href,
        shareImgUrl : "http://kotexcrm.umaman.com/html/img/share_photo.jpg"
    };
    WeixinShareSetting(op);
</script>
</body>
</html>