<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>高洁丝</title>
<meta name="keyword" content="高洁丝 无忧日历">
<meta name="description" content="高洁丝 无忧日历">

<!-- Mobile Setting Begin-->
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
<meta http-equiv="cleartype" content="on">
<!-- Mobile Setting End-->
<script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
<link rel="stylesheet" type="text/css"
	href="<?php echo $this->rootPath;?>html/css/reset.css" />
<link rel="stylesheet" type="text/css"
	href="<?php echo $this->rootPath;?>html/css/public.css?v=<?php $this->version;?>" />
<script type="text/javascript"
	src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
<script type="text/javascript"
	src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
<script type="text/javascript"
	src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php $this->version;?>"></script>
</head>
<body>
	<div class="page_box">
		<img src="<?php echo $this->rootPath;?>html/img/video/share1.jpg"
			width="100%" alt=""> <img
			src="<?php if(empty($this->photo)) {?><?php echo $this->rootPath;?>html/img/video/img5.jpg<?php }else{ echo $this->photo;}?>"
			alt="" class="img_ren"> <img
			src="<?php if(!empty($this->picture)){ echo $this->picture;} else {?><?php echo $this->rootPath;?>html/img/video/share2.png<?php }?>"
			class="img_share1" alt="">
	</div>
	<script type="text/javascript">
    seajs.use(["jquery","views.integral"],function($,integralPage){
        $(function(){
            integralPage.init();
        })
    })
</script>
<script type="text/javascript">
//     var shareArr = ['小伙伴们看过来','这是我今天的状态哦，求关注','<?php echo $this->shareLink;?>','<?php if(!empty($this->photo)){ echo $this->photo;}else{ echo 'http://140225-i0011.umaman.com/html/img/video/img5.jpg';}?>'];
//     document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
//         WeixinJSBridge.on('menu:share:timeline', function(argv){
//             WeixinJSBridge.invoke('shareTimeline',{
//                 "img_url":shareArr[3],
//                 "link":shareArr[2],
//                 "desc":shareArr[1],
//                 "title":shareArr[0]
//             },function(res){
//                 //alert('res');
//             });
//         });
//         WeixinJSBridge.on('menu:share:appmessage', function(argv){
//             WeixinJSBridge.invoke('sendAppMessage',{
//                 "appid":'',
//                 "img_url":shareArr[3],
//                 "link":shareArr[2],
//                 "desc":shareArr[1],
//                 "title":shareArr[0]
//             },function(res){
//                 //alert('res');
//             });
//         });
//         //WeixinJSBridge.call('hideOptionMenu');
//     });
 </script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/module.share.js?v=0.3"></script>
<script type="text/javascript">
    var op = {
        isHideButton : false,
        shareTitle : "这是我今日心情状态，求关注！",
        shareDescription : "想知道我今天的心情是晴是雨吗？关注我，了解我哦！",
        shareLink : '<?php echo $this->shareLink;?>',
        shareImgUrl : 'http://kotexcrm.umaman.com/html/img/share_photo.jpg'
    };
    WeixinShareSetting(op);
</script>
</body>
</html>