<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝 无忧日历</title>
    <meta name="keyword" content="高洁丝 无忧日历">
    <meta name="description" content="高洁丝 无忧日历">

	<meta http-equiv="Expires" Content="0">
	<!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css?v=<?php echo $this->version;?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=<?php echo $this->version;?>"/>
    
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js"></script>
</head>
<body>
<div class="page_box">
    <img src="<?php echo $this->rootPath;?>html/img/video/share2.jpg" width="100%" alt="">
    <img src="<?php if(empty($this->photo)) {?><?php echo $this->rootPath;?>html/img/video/img6.jpg<?php }else{ echo $this->photo;}?>" alt="" class="img_ren1">
    <img src="<?php if(!empty($this->picture)){ echo $this->picture; } else {echo $this->rootPath;?>html/img/video/share3.png<?php }?>" class="img_share2" alt="">
    <a href="http://mp.weixin.qq.com/s?__biz=MjM5MjUxMTQ3Mg==&mid=200144027&idx=1&sn=ce02c97dbb6b905679c692a34da6ecc8#rd"><img src="<?php echo $this->rootPath;?>html/img/video/share4.png" class="img_share3 btn_care" alt=""></a>
<!--     <div class="share_tan">
        <img src="<?php echo $this->rootPath;?>html/img/video/img_share.jpg" class="img100" alt="">
        <img src="<?php echo $this->rootPath;?>html/img/video/btn.gif" class="btn_know" alt="">
    </div> -->
</div>
<script type="text/javascript">
    // seajs.use(["jquery","views.integral"],function($,integralPage){
    //     $(function(){
    //         integralPage.init();
    //     })
    // })
</script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>

</body>
</html>