<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝</title>
    <meta name="keyword" content="我的优惠">
    <meta name="description" content="我的优惠">

    <!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=00"/>
    <script>var web_path = '<?php echo $this->rootPath;?>html/';var redirect = '<?php echo $this->redirect;?>';</script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php echo $this->version;?>"></script>
</head>
<body>

<div class="page_box" id="inputInfo_box">
    <div class="page_bg"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/inputInfo/inputInfo_bg.jpg?v=1.1"></div>
    <div class="page_wrap">
        <div class="wrap_header"><img class="header_img fullWidth" src="<?php echo $this->rootPath;?>html/img/inputInfo/inputInfo_title.png?v=1.1"></div>
        <div class="wrap_inputInfo">
            <div class="input_info_box">
                <img class="input_info_icon top_icon" src="<?php echo $this->rootPath;?>html/img/inputInfo/icon_top.png">
                <img class="input_info_icon right_icon" src="<?php echo $this->rootPath;?>html/img/inputInfo/icon_right.png">
                <img class="input_info_icon left_icon" src="<?php echo $this->rootPath;?>html/img/inputInfo/icon_left.png">
                <img class="input_info_icon bottom_icon" src="<?php echo $this->rootPath;?>html/img/inputInfo/icon_bottom.png">
                <div class="input_info">
                    <ul class="input_info_list">
                        <li class="birthday_lable"><label><span class="fsBig">你的生日：</span><input type="date" name="birthday" value="<?php if(isset($this->userInfo['birthday'])){ echo date("Y-m-d",$this->userInfo['birthday']->sec);} ?>"></label></li>
                        <li class="lastTime_lable"><label><span class="fsBig">最近一次月经：</span><input type="date" name="lastTime" placeholder="哪天来的" value="<?php if(isset($this->userInfo['last_time'])){ echo date("Y-m-d",$this->userInfo['last_time']->sec);} ?>"/></label></li>
                        <li class="menstruation_lable"><label><span class="fsBig">经期天数：</span><input type="number" name="menstruation" placeholder="来大姨妈天数" value="<?php if(isset($this->userInfo['menstruation'])){ echo $this->userInfo['menstruation'];} ?>"/></label></li>
                        <li class="period_lable"><label><span class="fsBig">周期天数：</span><input type="number" name="period" placeholder="两次月经第一天间隔天数"  value="<?php if(isset($this->userInfo['period'])){ echo $this->userInfo['period'];} ?>"/></label></li>
                    </ul>
                </div>
            </div>
            <div class="submit_info"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/inputInfo/inputInfo_btn.png?v=1.1"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    seajs.use(["jquery","views.inputinfo"],function($,inputinfoPage){
        $(function(){
            inputinfoPage.init();
        })
    })
</script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>

</body>
</html>