<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>高洁丝</title>
    <meta name="keyword" content="高洁丝 积分纪录">
    <meta name="description" content="高洁丝 积分纪录">

    <!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=<?php $this->version;?>"/>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php $this->version;?>"></script>
</head>
<body>
<div class="page_rili">
    <img src="<?php echo $this->rootPath;?>html/img/integral/bg.jpg" width="100%" alt="">
    <div class="integral">
        <div class="integral_1">
            <img src="<?php echo $this->rootPath;?>html/img/integral/img1.jpg" alt="" class="img100">
            <img src="<?php echo $this->weixinUserInfo['headimgurl'];?>" alt="" class="face">
            <span class="jifen"><?php echo $this->total;?></span>
        </div>
        <div class="integral_2">
            <img src="<?php echo $this->rootPath;?>html/img/integral/img2.png" alt="" class="img100">
            <div class="integral_list">
                <ul>
                <?php 
                    if(!empty($this->pointRecords)) {
                        foreach($this->pointRecords as $record) {
                ?>
                    <li><span class="span1"><?php echo date("Y-m-d",$record['__CREATE_TIME__']->sec);?></span><span class="span2"><?php 
                    switch($record['reason']){ 
                        case 1:
                            echo '关注奖励积分'; 
                            break;
                        case 2:
                            echo '邀请好友奖励积分';
                            break;
                        case 3:
                            echo '输入购买产品Code';
                            break;  
                    }
                    ?></span><span class="span3"><?php echo $record['points'];?></span></li>
                <?php }
                    } 
                ?>
                </ul>
            </div>
            <img src="<?php echo $this->rootPath;?>html/img/integral/img3.png" alt="" class="img100">
        </div>
        <p class="p_integral">
            *积分特权丰厚礼遇，<strong>四月</strong>即将开启，敬请擦亮双眼，翘首以待！
        </p>
    </div>
</div>
<script type="text/javascript">
    document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
        WeixinJSBridge.call('hideOptionMenu');
    });
    seajs.use(["jquery","views.integral"],function($,integralPage){
        $(function(){
            integralPage.init();
        })
    });
</script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/module.share.js?v=0.3"></script>
<script type="text/javascript">
    var op = {
        isHideButton : false,
        shareTitle : "姐妹们，一起来赚积分吧！",
        shareDescription : "小伙伴快来赚积分吧！更多好礼等你来拿哦！",
        shareLink : location.href,
        shareImgUrl :  "http://kotexcrm.umaman.com/html/img/share_jifen.jpg"
    };
    WeixinShareSetting(op);
</script>
</body>
</html>