<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>教授救我</title>
    <meta name="keyword" content="教授救我 - 高洁丝">
    <meta name="description" content="教授救我 - 高洁丝">

    <!-- Mobile Setting Begin-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="cleartype" content="on">
    <!-- Mobile Setting End-->
    <script>var web_path = '<?php echo $this->rootPath;?>html/';</script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/reset.css?v=<?php echo $this->version;?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/public.css?v=<?php echo $this->version;?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->rootPath;?>html/css/guaguaka.css?v=0.2"/>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/libs/seajs-log.js"></script>
    <script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/config.js?v=<?php echo $this->version;?>"></script>
    <script>var result = <?php echo $this->rst;?> || "";</script>
</head>
<body>
<div class="page_box" id="guaguaka_box">
    <div class="page_wrap">
        <div class="wrap_user">
            <div class="guaguaka_pic">
                <img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/guagua/guagua_img1.jpg">
                <img class="fullWidth hide" src="<?php echo $this->rootPath;?>html/img/guagua/guagua_result_img1.jpg">
            </div>
            <div class="scratch_card">
                <img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/guagua/guagua_default.jpg">
                <div id="card" data-result="0"></div>
                <a class="play_again" href="#"><img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/guagua/guagua_playAgain.png" /></a>
            </div>
            <div class="guaguaka_pic">
                <img class="fullWidth" src="<?php echo $this->rootPath;?>html/img/guagua/guagua_img2.jpg">
                <img class="fullWidth hide" src="<?php echo $this->rootPath;?>html/img/guagua/guagua_result_img2.jpg">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    seajs.use(["jquery","views.guaguaka"],function($,guaguaka){
        $(function(){
            guaguaka.init();
        })
    })
</script>

<script type="text/javascript" src="<?php echo $this->rootPath;?>html/js/module.share.js?v=0.3"></script>
<script type="text/javascript">
    var opFail = {
        isHideButton : false,
        shareTitle : "教授满满的爱，我快挡不住了",
        shareDescription : "姐妹们，看到都教授对我那么贴心，可别吃醋哦！或者，你们也来体验下？",
        shareLink : 'http://kotexcrm.umaman.com/weixin/sns/index?scope=snsapi_base&redirect=/campaign/jsjw/index',
        shareImgUrl : 'http://kotexcrm.umaman.com/html/img/share_gua.jpg'
    };
    var opSucc = {
        isHideButton : false,
        shareTitle : "羡慕吧！我有来自星星的福利哦！",
        shareDescription : "都教授对人家好贴心呢，来大姨妈还赏我优惠券！你也想要吗？",
        shareLink : 'http://kotexcrm.umaman.com/weixin/sns/index?scope=snsapi_base&redirect=/campaign/jsjw/index',
        shareImgUrl : 'http://kotexcrm.umaman.com/html/img/share_gua.jpg'
    };
    var op = opFail;
    console.info(op);
    WeixinShareSetting(op);
</script>

<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F567d502f408715e97b9678fa462dbcd6' type='text/javascript'%3E%3C/script%3E"));
</script>
</body>
</html>
