<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no; address=no; email=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>微信商城-购物车</title>
    <link rel="stylesheet" href="<?php echo $this->getResourceUrl()?>css/main.css?<?php echo time();?>">
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/libs/jquery-2.0.3.min.js"></script>
    <script type="text/javascript">
		var web_path = "<?php echo $this->config['global']['path']?>";
	</script>
</head>
<body>
	购物车一览
	
</body>
</html>