<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>微信商城</title>
    <meta name="description" content="">
    <!-- 移动平台-->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no, address=no, email=no">
    <meta http-equiv="cleartype" content="on">


    <!--For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94-->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="">


    <link rel="stylesheet" type="text/css" href="<?php echo $this->getResourceUrl()?>css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getResourceUrl()?>css/style.css"/>
    <script type="text/javascript">
      var web_path = "<?php echo $this->config['global']['path']?>";
      var html_web_path = "<?php echo $this->getResourceUrl()?>";
    </script>
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/seajs/sea.js"></script>
    <script type="text/javascript" src="<?php echo $this->getResourceUrl()?>js/seajs/seajsConfig.js"></script>
</head>
<body>
    <div class="wrapper" id="cart">
       <header id="header">
           <a href="javascript:window.history.go(-1);" class="btn-back"></a>
           <span class="headerTitle">购物车结算</span>
       </header>
       <div class="container">

          <?php if(!empty($this->cart)){?>
          <div class="list">
	           <?php foreach ($this->cart as $gid =>$goods) {?>
            
            <div class="list-item" gid="<?php echo $gid ?>"  data-prize="<?php echo showMoney($goods['prize']/100)?>">
              <div class="list-item-cont">
                <div class="checkbox <?php if($goods['stock_num']>0){?>checked<?php }else{?>disabled<?php }?>"></div>
                <img class="pic" src="<?php echo $goods['pic']?>" alt="">
                <div class="detail">
                  <strong><?php echo $goods['name']?> </strong>
                  <p>规格：<?php echo $goods['spec']?></p>
                  <b>￥<?php echo showMoney($goods['prize']/100)?></b>
                </div>
              </div>
              
              <div class="list-item-ctrl">
                <div class="laji">
                  <img src="<?php echo $this->getResourceUrl()?>images/cart/laji.png" alt="">
                </div>
                <div class="num">
                  数量 
                  <div class="numbox">
                    <div class="numbox-left">-</div>
                    <div class="numbox-center">
                      <input type="text" value="<?php echo $goods['num']?>" max="999" maxlength="3">
                    </div>
                    <div class="numbox-right">+</div>
                  </div>
                </div>
                <?php if($goods['stock_num']<=0){?>
                <div class="total">暂时缺货</span>
                <?php }else{?>
                <div class="total">共计：<span><?php echo showMoney($goods['amount']/100)?></span>
                <?php }?>
                </div>

              </div>
            </div>

    	       <?php }?>
          </div>

           <div class="zongji">
            <div class="checkbox checked"><span>全选</span></div>
            <div class="zongji-right">
              <p>总计：<strong>￥<span><?php echo showMoney($this->total/100)?></span></strong></p>
              <p>(不含快递费)</p>
            </div>
          </div>
          <a href="javascript:;" class="btn-ljjs">立即结算</a>   
          <?php } else { ?>

          <div class="zongji">当前购物车为空。</div>
          <a href="javascript:;" class="btn-ljjs btn-disabled">立即结算</a>   
          <?php } ?>
       </div>
    </div>
    
    <div class="pop" id="pop-confirm">
    	<p>确认删除该商品?</p>
        <div><a class="popUpBtn" data-rule="close" href="javascript:;">取消</a>&nbsp;&nbsp;<a class="popUpBtn" data-rule="confirm" href="javascript:;">确定</a></div>
    </div>
    
    <script type="text/javascript">
       seajs.use("app/views-cart");
    </script>
</body>
</html>